package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);

    /*
    * 根据商品ID跟用户ID查看商品（查看商品是否存在购物车）
    * */
    Cart selectProductByUserIdAndProductId(@Param("userId") Integer userId,@Param("productId") Integer productId);

    /*
    * 查询用户的购物车信息
    * */
    List<Cart> selectCartByUserId(@Param("userId")Integer userId);

    /*
    * 根据用户Id查找未选中的商品
    * */
    int selectNoCheckProduct(@Param("userId")Integer userId);
    /*
    *
    * 删除用户购物车中的商品
    * */
    int deleteProductByUserIdAndProductIds(@Param("userId") Integer userId,@Param("list") List<Integer> list);
    /*
    * 根据用户ID选中某个商品
    * */
    int choiceProductByUserId(@Param("userId")Integer userId,@Param("productId") Integer productId,@Param("check")Integer check);
    /*
    * 统计用户购物车中商品数量的总和
    * */
    int countProductNumber(@Param("userId")Integer userId);
    /*
    * 查看用户购物车中以选中的商品
    * */
    List<Cart> selectcheckedproduct(@Param("userId") Integer userId);
    /*
    * 清空购物车中的商品
    * */
    int batchDelete(@Param("cartList")List<Cart> cartList);
}