package com.neuedu.dao;


import com.neuedu.pojo.Product;
import com.neuedu.pojo.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);
    /**
     *
     * 判断用户名是否存在
     *
     * */
    int testuser(@Param("username") String username);
    /**
     *
     * 判断邮箱是否存在
     *
     * */
    int testemail(@Param("email") String email);
    /*
    *
    * 判断密码是否正确
    * */
    User test1(@Param("username") String username,@Param("password") String password);

    User testUP(@Param("username") String username,@Param("password") String password);

    int checkquestion(@Param("username") String username,@Param("question") String question,@Param("answer") String answer);

    int ModifyPassword(@Param("username") String username,@Param("newpassword") String newpassword);

    int update_information(@Param("user")User user);

    String findquestionByUsername(@Param("username") String username);

    int changePasswordFotget(@Param("username") String username,@Param("newpassword") String newpassword);





}